import {
  BundledAssetIdSchema,
  type BundledAssetId,
  type BundledAssetSpec,
} from "@tileborne/runtime";
import { Schema } from "effect";

import { PLUGIN_ID } from "../constants.js";

const PLAYER_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAASUExURQAAAEregAAAABRTLUregP///3NYjD4AAAADdFJOUwDcRkhEqmgAAAABYktHRAX4b+nHAAAAB3RJTUUH6gYIER4A+Fq5kwAAAFhJREFUOMtjYBj0QACrqCAYCOAQx5RhhEkIooozGyMAcTpw24HbVQwMLC4iDlg9wuLiMioxKgEDCtgElaAATZJJCQGwqkfXg6wBVQsuHbjtwOkqPP6gHAAADSkhqdvW9RMAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDYtMDhUMTc6Mjk6MTUrMDA6MDBKNfIyAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA2LTA4VDE3OjI5OjE1KzAwOjAwO2hKjgAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNi0wOFQxNzozMDowMCswMDowMM90sGIAAAAASUVORK5CYII=";

const PROJECTILE_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAVUExURQAAADuC9mCl+gAAAJPF/fj6/P///3l+SPEAAAAEdFJOUwCqUEZCeAfdAAAAAWJLR0QGYWa4fQAAAAd0SU1FB+oGCBEdJO90DoEAAABJSURBVDjLY2AYBaOAWMDiggQccEmEhkJFBYEAqwQOo5iUwEBhoL05kMAAm6AxFKBJMhsjAFb16HqQNaBqwaUDtx04XYXHH5QDAH8tH+1/BGDGAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDI2LTA2LTA4VDE3OjI5OjE1KzAwOjAwSjXyMgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0wNi0wOFQxNzoyOToxNSswMDowMDtoSo4AAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDYtMDhUMTc6Mjk6MzYrMDA6MDAfsHaxAAAAAElFTkSuQmCC";

const SHIELD_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAVUExURQAAADi9+Di9+Di9+ODy/gAAAP////03PqMAAAAGdFJOUwA80iPcRg4TtQsAAAABYktHRAZhZrh9AAAAB3RJTUUH6gYIER0k73QOgQAAAMFJREFUOMvNk8ENwyAMReHQO6jKALQTIHeCxgOkB++/Sg24CApW0vbSLyWC//KdEIwxfy83da1PGv3kBr7c7PkwZkqdMFbj+RngCvBWzGY/AegjPAMBsYuUQAbQAlsCBcSmlgQKaCMSEBD3gZVKAqC+pIJVAYjrFNwQ8SDwlyz28Z5HwX1bau+r9HUMK//8J+r7oe6guud6l6h9pXai3rv0qIC2xj8RvcBC1CWoZDwP2kSKsJZ870+OIdFmJpqav+sJTBxVwU6GLy0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDYtMDhUMTc6Mjk6MTUrMDA6MDBKNfIyAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA2LTA4VDE3OjI5OjE1KzAwOjAwO2hKjgAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNi0wOFQxNzoyOTozNiswMDowMB+wdrEAAAAASUVORK5CYII=";

const SCAN_PULSE_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURQAAAGCl+gAAAGCl+v///7lOTrIAAAADdFJOUwBGRsPqyPgAAAABYktHRASPaNlRAAAAB3RJTUUH6gYIER4A+Fq5kwAAAIhJREFUOMvdklEKgCAQRLUTOHUB2xMk3v9ukUo0uhYRRDQ/wTyeiI0xP8yithYIgNpvAFqfQE2wA9cKGbCCKZYEUuwRgEHIR00MQMBdA8sArwJESnCfuNX9Rzz9UTrIIyljoJl0V9LdVXeJg8wFiBAQSWTrxZOQMuZPZezxplUa4eB4o0Qtn2cF2lcv1bhx1RMAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDYtMDhUMTc6Mjk6MTUrMDA6MDBKNfIyAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA2LTA4VDE3OjI5OjE1KzAwOjAwO2hKjgAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNi0wOFQxNzozMDowMCswMDowMM90sGIAAAAASUVORK5CYII=";

const DECOY_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURQAAACLT7g8XKgAAAP///8YmprEAAAAEdFJOUwCW3Eb4P8xuAAAAAWJLR0QEj2jZUQAAAAd0SU1FB+oGCBEdJO90DoEAAACKSURBVDjL5ZLRDYAgDEQhLgAyAZ2AhP13E1rR0HJfRn+8D0jueBQozv1JYW3HpgD8VeIliACwyAAMcvkaYS/bgHciymavHuxEZAIBBAkq6AAjLwX+rC3VPy6Obw7fCr4u7AfuIOw5/CX4X1XxU5ntrVZOUpvn9azEY1HALUtUQ0yIPtVq/dDSfK4DkzImbY5yMy4AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDYtMDhUMTc6Mjk6MTUrMDA6MDBKNfIyAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA2LTA4VDE3OjI5OjE1KzAwOjAwO2hKjgAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNi0wOFQxNzoyOTozNiswMDowMB+wdrEAAAAASUVORK5CYII=";

const TRAP_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURQAAAPWeCwAAAFAsAP///+igs8wAAAADdFJOUwDcRkhEqmgAAAABYktHRASPaNlRAAAAB3RJTUUH6gYIER0k73QOgQAAAJJJREFUOMvtkssRgCAMRNUK+DTgpAIZ+u9NiTIkkNWDHt0DzuzykgBO069v5UzXsxzwx8R7O5lb4AGgEQkoJEs/bqKSSGJyslJuvqhVWuTEPn9077L1AruhjiR3Y9XytZF7JG57oKnsc8CT47uCtwvfA78gfHP4lyxEpx+IVECswOuqAaGRoIFQSDeVub/KNN9rBx7BIekiT3QAAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDI2LTA2LTA4VDE3OjI5OjE1KzAwOjAwSjXyMgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0wNi0wOFQxNzoyOToxNSswMDowMDtoSo4AAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDYtMDhUMTc6Mjk6MzYrMDA6MDAfsHaxAAAAAElFTkSuQmCC";

const LOOT_CRATE_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURQAAAAAAAHwtEvlzFv///zKI0bMAAAACdFJOUwBG6SwpnQAAAAFiS0dEBI9o2VEAAAAHdElNRQfqBggRHSTvdA6BAAAAgElEQVQ4y+2S3Q3AIAiE6QbtCrLBsf9ubQz+oJBomr71Hvk4RIDo19dKRkuApckAtDgMkGZhC6oFtpRUC48AxTACSTnOM8jFWBwArTeBJ519AIgPtOUNR/RG2FX0D6hrmpW2JKvTDfcRbTDc+fZdHVev/kb7+EmBhazc/CI3+F43AHNDh+dPVl0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDYtMDhUMTc6Mjk6MTUrMDA6MDBKNfIyAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA2LTA4VDE3OjI5OjE1KzAwOjAwO2hKjgAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNi0wOFQxNzoyOTozNiswMDowMB+wdrEAAAAASUVORK5CYII=";

const WEAPON_RIFLE_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAASUExURQAAAAAAAA8XKh8pN5SjuP///9yBWvcAAAACdFJOUwBG6SwpnQAAAAFiS0dEBfhv6ccAAAAHdElNRQfqBggRHSTvdA6BAAAAU0lEQVQ4y2NgGAWjACdgUlIiLGGMDIyUlIxxSKi4uJAogdMohARUzgCbc4mQQAMDKgEGAtgEBaEATZJREAGwqkfXg6wBVQsuHbjtwOkqPP6gHAAA5qsfRV6JxWUAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDYtMDhUMTc6Mjk6MTUrMDA6MDBKNfIyAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA2LTA4VDE3OjI5OjE1KzAwOjAwO2hKjgAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNi0wOFQxNzoyOTozNiswMDowMB+wdrEAAAAASUVORK5CYII=";
const IMPACT_BURST_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAASUExURQAAAP7wigAAAP26dP7wiv///2v0drUAAAADdFJOUwDSRtbHh+YAAAABYktHRAX4b+nHAAAAB3RJTUUH6gYIER0k73QOgQAAAKFJREFUOMvlktEJwzAMRJU2Cwg8QNAEctsBbLr/TjVNRGLrRD6avx4Egt89HNkh+qfoFaAcQDmCeQczUNQJW0+9sBbVC2tTgfCtKhBad+LMQCCqDQCBpsQ5MQJcc8UgvbgH9+eWt72cGWd7RF8VzhFOHp1VeLqF8H2EN1gMDEr4l5QdjLtIy6M9S798EwMirm9gcYLFG+KMThkmhH0LXPw9Hz5qG59pOpZ4AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDI2LTA2LTA4VDE3OjI5OjE1KzAwOjAwSjXyMgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0wNi0wOFQxNzoyOToxNSswMDowMDtoSo4AAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDYtMDhUMTc6Mjk6MzYrMDA6MDAfsHaxAAAAAElFTkSuQmCC";
const SHADOW_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURQAAAA8XKgIGFwAAAP///6h2n/4AAAAEdFJOUwB4lkZR1ZZLAAAAAWJLR0QEj2jZUQAAAAd0SU1FB+oGCBEdJO90DoEAAABwSURBVDjL7ZHJDcAgDARBNGDoACqIRP+9RRyKD3mTR57JPBcP2CaEn09DXpg35jBmximvVhr1pS2UI/J5QkK48lZZiVKYCt8k8qHQgwHfgF3hOeDkeFd4uzf/0TeHjlNn3HrrSEEryMBvwK4WbvieE0CjJMVeXNPUAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDI2LTA2LTA4VDE3OjI5OjE1KzAwOjAwSjXyMgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNi0wNi0wOFQxNzoyOToxNSswMDowMDtoSo4AAAAodEVYdGRhdGU6dGltZXN0YW1wADIwMjYtMDYtMDhUMTc6Mjk6MzYrMDA6MDAfsHaxAAAAAElFTkSuQmCC";

const WHITE_PIXEL_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==";

const dataUrl = (base64: string): string => `data:image/png;base64,${base64}`;

const bundledAssetId = (assetKey: string): BundledAssetId =>
  Schema.decodeUnknownSync(BundledAssetIdSchema)(`${PLUGIN_ID}:${assetKey}`);

export const PLAYER_TEXTURE_ASSET_ID = bundledAssetId("default-pet");
export const PROJECTILE_TEXTURE_ASSET_ID = bundledAssetId("projectile-bolt");
export const SHIELD_TEXTURE_ASSET_ID = bundledAssetId("shield-burst");
export const SCAN_PULSE_TEXTURE_ASSET_ID = bundledAssetId("scan-pulse");
export const DECOY_TEXTURE_ASSET_ID = bundledAssetId("decoy");
export const TRAP_TEXTURE_ASSET_ID = bundledAssetId("trap");
export const LOOT_CRATE_TEXTURE_ASSET_ID = bundledAssetId("loot-crate");
export const WEAPON_RIFLE_TEXTURE_ASSET_ID = bundledAssetId("weapon-rifle");
export const IMPACT_BURST_TEXTURE_ASSET_ID = bundledAssetId("impact-burst");
export const SHADOW_TEXTURE_ASSET_ID = bundledAssetId("shadow");
export const UI_PIXEL_TEXTURE_ASSET_ID = bundledAssetId("ui-pixel");

export const createBattleRoyaleBundledAssets = (): readonly BundledAssetSpec[] => [
  {
    assetId: PLAYER_TEXTURE_ASSET_ID,
    path: dataUrl(PLAYER_PNG_BASE64),
    mime: "image/png",
    width: 48,
    height: 48,
  },
  {
    assetId: PROJECTILE_TEXTURE_ASSET_ID,
    path: dataUrl(PROJECTILE_PNG_BASE64),
    mime: "image/png",
    width: 48,
    height: 48,
  },
  {
    assetId: SHIELD_TEXTURE_ASSET_ID,
    path: dataUrl(SHIELD_PNG_BASE64),
    mime: "image/png",
    width: 48,
    height: 48,
  },
  {
    assetId: SCAN_PULSE_TEXTURE_ASSET_ID,
    path: dataUrl(SCAN_PULSE_PNG_BASE64),
    mime: "image/png",
    width: 48,
    height: 48,
  },
  {
    assetId: DECOY_TEXTURE_ASSET_ID,
    path: dataUrl(DECOY_PNG_BASE64),
    mime: "image/png",
    width: 48,
    height: 48,
  },
  {
    assetId: TRAP_TEXTURE_ASSET_ID,
    path: dataUrl(TRAP_PNG_BASE64),
    mime: "image/png",
    width: 48,
    height: 48,
  },
  {
    assetId: LOOT_CRATE_TEXTURE_ASSET_ID,
    path: dataUrl(LOOT_CRATE_PNG_BASE64),
    mime: "image/png",
    width: 48,
    height: 48,
  },
  {
    assetId: WEAPON_RIFLE_TEXTURE_ASSET_ID,
    path: dataUrl(WEAPON_RIFLE_PNG_BASE64),
    mime: "image/png",
    width: 48,
    height: 48,
  },
  {
    assetId: IMPACT_BURST_TEXTURE_ASSET_ID,
    path: dataUrl(IMPACT_BURST_PNG_BASE64),
    mime: "image/png",
    width: 48,
    height: 48,
  },
  {
    assetId: SHADOW_TEXTURE_ASSET_ID,
    path: dataUrl(SHADOW_PNG_BASE64),
    mime: "image/png",
    width: 48,
    height: 48,
  },
  {
    assetId: UI_PIXEL_TEXTURE_ASSET_ID,
    path: dataUrl(WHITE_PIXEL_PNG_BASE64),
    mime: "image/png",
    width: 1,
    height: 1,
  },
];
