export const PROJECT_PATH = '/projects/demo/world.ldtk';

export const minimalLdtkProject = {
  jsonVersion: '1.5.3',
  iid: 'proj-iid-1',
  identifier: 'DemoWorld',
  externalLevels: false,
  defs: {
    tags: ['outdoor'],
    enums: [
      {
        uid: 10,
        identifier: 'Biome',
        values: [{ id: 'Grass', tileIds: [1] }],
      },
    ],
    tilesets: [
      {
        uid: 1,
        identifier: 'Terrain',
        relPath: 'terrain.png',
        tileGridSize: 16,
        padding: 1,
        spacing: 1,
        __cWid: 4,
        __cHei: 2,
        pxWid: 74,
        pxHei: 36,
        tags: ['terrain'],
        enumTags: [{ enumValueId: 'Grass', tileIds: [1] }],
        customData: [],
        savedSelections: [],
      },
    ],
    layers: [
      {
        __type: 'IntGrid',
        uid: 100,
        identifier: 'TerrainGrid',
        gridSize: 16,
        intGridValues: [
          { value: 1, identifier: 'grass', color: '#00ff00' },
          { value: 2, identifier: 'water', color: '#0000ff' },
        ],
      },
      {
        __type: 'AutoLayer',
        uid: 101,
        identifier: 'TerrainAuto',
        gridSize: 16,
        tilesetDefUid: 1,
        autoSourceLayerDefUid: 100,
        autoRuleGroups: [
          {
            uid: 1000,
            active: true,
            name: 'GrassEdges',
            rules: [
              {
                uid: 2001,
                active: true,
                size: 3,
                pattern: [0, 1, 0, 1, 1, 2, 0, 2, 0],
                tileRectsIds: [[1, 0]],
                tileMode: 'Single',
                checker: 'None',
                perlinActive: false,
                chance: 1,
                xModulo: 1,
                yModulo: 1,
                flipX: false,
                flipY: false,
                alpha: 1,
                breakOnMatch: true,
                invalidated: false,
                pivotX: 0,
                pivotY: 0,
                tileRandomXMin: 0,
                tileRandomXMax: 0,
                tileRandomYMin: 0,
                tileRandomYMax: 0,
                tileXOffset: 0,
                tileYOffset: 0,
                xOffset: 0,
                yOffset: 0,
              },
              {
                uid: 2002,
                active: true,
                size: 3,
                pattern: [0, 0, 0, 0, 1, 0, 0, 0, 0],
                tileRectsIds: [[2, 0]],
                tileMode: 'Stamp',
                checker: 'Horizontal',
                perlinActive: true,
                chance: 0.5,
                xModulo: 2,
                yModulo: 1,
                flipX: true,
                flipY: false,
                alpha: 1,
                breakOnMatch: true,
                invalidated: false,
                pivotX: 0,
                pivotY: 0,
                tileRandomXMin: 0,
                tileRandomXMax: 0,
                tileRandomYMin: 0,
                tileRandomYMax: 0,
                tileXOffset: 0,
                tileYOffset: 0,
                xOffset: 0,
                yOffset: 0,
              },
            ],
            biomeRequirementMode: 0,
            isOptional: false,
            requiredBiomeValues: [],
            usesWizard: false,
          },
        ],
      },
      {
        __type: 'Tiles',
        uid: 102,
        identifier: 'Ground',
        gridSize: 16,
        tilesetDefUid: 1,
      },
      {
        __type: 'Entities',
        uid: 103,
        identifier: 'Objects',
        gridSize: 16,
      },
    ],
    entities: [
      {
        uid: 500,
        identifier: 'PlayerSpawn',
        width: 16,
        height: 16,
        color: '#ff0000',
        pivotX: 0.5,
        pivotY: 0.5,
        tags: ['spawn'],
        fieldDefs: [],
        nineSliceBorders: [],
        allowOutOfBounds: false,
        exportToToc: false,
        fillOpacity: 1,
        hollow: false,
        keepAspectRatio: false,
        limitBehavior: 'DiscardOldOnes',
        limitScope: 'PerLevel',
        lineOpacity: 1,
        maxCount: 1,
        renderMode: 'Rectangle',
        resizableX: false,
        resizableY: false,
        showName: true,
        tileOpacity: 1,
        tileRenderMode: 'Cover',
      },
      {
        uid: 501,
        identifier: 'Crate',
        width: 16,
        height: 16,
        color: '#aa5500',
        pivotX: 0.5,
        pivotY: 0.5,
        tags: ['prop'],
        fieldDefs: [],
        nineSliceBorders: [],
        allowOutOfBounds: false,
        exportToToc: false,
        fillOpacity: 1,
        hollow: false,
        keepAspectRatio: false,
        limitBehavior: 'DiscardOldOnes',
        limitScope: 'PerLevel',
        lineOpacity: 1,
        maxCount: 0,
        renderMode: 'Rectangle',
        resizableX: false,
        resizableY: false,
        showName: true,
        tileOpacity: 1,
        tileRenderMode: 'Cover',
      },
    ],
  },
  levels: [
    {
      identifier: 'Level_0',
      uid: 1000,
      pxWid: 32,
      pxHei: 32,
      iid: 'level-iid-1',
      worldDepth: 0,
      worldX: 0,
      worldY: 0,
      __bgColor: '#000000',
      __neighbours: [],
      fieldInstances: [],
      __smartColor: '#ffffff',
      bgPivotX: 0.5,
      bgPivotY: 0.5,
      useAutoIdentifier: true,
      layerInstances: [
        {
          __identifier: 'TerrainGrid',
          __type: 'IntGrid',
          __uid: 100,
          __gridSize: 16,
          __cWid: 2,
          __cHei: 2,
          intGridCsv: [1, 2, 1, 2],
        },
        {
          __identifier: 'Ground',
          __type: 'Tiles',
          __uid: 102,
          __gridSize: 16,
          __tilesetDefUid: 1,
          gridTiles: [{ px: [0, 0], src: [0, 0], f: 0, d: [0] }],
        },
        {
          __identifier: 'Objects',
          __type: 'Entities',
          __uid: 103,
          __gridSize: 16,
          entityInstances: [
            {
              __identifier: 'PlayerSpawn',
              defUid: 500,
              px: [16, 16],
              width: 16,
              height: 16,
              fieldInstances: [{ __identifier: 'team', __value: 1, defId: 1 }],
            },
            {
              __identifier: 'Crate',
              defUid: 501,
              px: [0, 0],
              width: 16,
              height: 16,
              fieldInstances: [],
            },
          ],
        },
      ],
    },
  ],
} as const;

export const externalLevelProject = {
  ...minimalLdtkProject,
  externalLevels: true,
  levels: [
    {
      identifier: 'ExternalLevel',
      uid: 2000,
      pxWid: 16,
      pxHei: 16,
      iid: 'level-iid-2',
      worldDepth: 0,
      worldX: 0,
      worldY: 0,
      __bgColor: '#000000',
      __neighbours: [],
      fieldInstances: [],
      __smartColor: '#ffffff',
      bgPivotX: 0.5,
      bgPivotY: 0.5,
      useAutoIdentifier: true,
      externalRelPath: 'levels/ExternalLevel.ldtkl',
      layerInstances: null,
    },
  ],
} as const;

export const externalLevelFile = {
  identifier: 'ExternalLevel',
  uid: 2000,
  pxWid: 16,
  pxHei: 16,
  layerInstances: [
    {
      __identifier: 'Ground',
      __type: 'Tiles',
      __uid: 102,
      __gridSize: 16,
      __tilesetDefUid: 1,
      gridTiles: [{ px: [0, 0], src: [1, 0], f: 0, d: [0] }],
    },
  ],
} as const;
