export {
  BATTLE_ROYALE_CORE_VISUAL_PLACEABLE_IDS,
  BATTLE_ROYALE_VISUAL_ROLE_POLICY,
  DEFAULT_BATTLE_ROYALE_VISUAL_ASSET_ROLES,
  DEFAULT_BATTLE_ROYALE_VISUAL_ROLE_DEFINITIONS,
  resolveBattleRoyaleVisualAssetRoles,
} from "../content-assets.js";
